-- LOCAL TEST ONLY: mimics a customized Supabase project with bigint product IDs
-- and a freshly recreated UUID-keyed settings table.
ALTER ROLE service_role BYPASSRLS;
CREATE TABLE public.staff_users(user_id uuid PRIMARY KEY REFERENCES auth.users(id),role text DEFAULT 'owner');
CREATE FUNCTION public.is_staff(p_user_id uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$
 SELECT EXISTS(SELECT 1 FROM public.staff_users WHERE user_id=p_user_id);
$$;
GRANT EXECUTE ON FUNCTION public.is_staff(uuid) TO authenticated, service_role;
CREATE TABLE public.settings (
 id uuid PRIMARY KEY DEFAULT pg_catalog.gen_random_uuid(),
 business_name text NOT NULL DEFAULT '@thetieguy',
 availability text NOT NULL DEFAULT 'normal',
 unavailable_message text NOT NULL DEFAULT 'Unavailable'
);
INSERT INTO public.settings DEFAULT VALUES;
CREATE TABLE public.products(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name text NOT NULL,
 category text NOT NULL,
 price numeric(12,2) NOT NULL,
 stock integer NOT NULL DEFAULT 0,
 sizes text[] NOT NULL DEFAULT ARRAY['One size']::text[],
 description text NOT NULL DEFAULT '',
 image_url text NOT NULL DEFAULT '',
 active boolean NOT NULL DEFAULT true
);
INSERT INTO public.products(id,name,category,price,stock)
 VALUES(9223372036854775807,'Bigint ID necktie','Neckties',119.99,2);
